name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --build-arg NEXT_PUBLIC_BACKEND_URL=${{ vars.NEXT_PUBLIC_BACKEND_URL }} --build-arg NEXT_PUBLIC_FRONTEND_URL=${{ vars.NEXT_PUBLIC_FRONTEND_URL }} --build-arg NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${{ vars.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }} --build-arg NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=${{ vars.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET }}  --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/artsphere:latest
    - name: Push the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        docker push ${{ secrets.DOCKER_USERNAME }}/artsphere:latest
